version: "3.9"

services:
  app:
    image: tomcat:10.1-jdk17
    container_name: clinique_app
    restart: unless-stopped
    depends_on:
      db:
        condition: service_started
      builder:
        condition: service_healthy
    ports:
      - "8085:8080"
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=clinique-db
      - DB_USER=clinique
      - DB_PASSWORD=clinique123
      - CATALINA_OPTS=-Djava.security.egd=file:/dev/./urandom -Dorg.apache.tomcat.util.scan.StandardJarScanFilter.jarsToSkip=*.jar -Dorg.apache.tomcat.util.scan.StandardJarScanFilter.jarsToScan=ROOT.jar
    volumes:
      - ./src/main/webapp:/usr/local/tomcat/webapps/ROOT
      - ./target/clinique-digitale-1.0-SNAPSHOT/WEB-INF/lib:/usr/local/tomcat/webapps/ROOT/WEB-INF/lib
      - class_data:/usr/local/tomcat/webapps/ROOT/WEB-INF/classes
    networks:
      - clinique_net

  db:
    image: postgres:15
    container_name: clinique_db
    restart: always
    environment:
      POSTGRES_USER: clinique
      POSTGRES_PASSWORD: clinique123
      POSTGRES_DB: clinique-db
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - clinique_net

  builder:
    image: maven:3.9.5-eclipse-temurin-17
    container_name: clinique_builder
    restart: unless-stopped
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - ./m2_cache:/root/.m2
      - class_data:/usr/src/app/target/classes
    command: >
      bash -c "
        mvn -q -DskipTests -T 1C package || true && \
        while true; do \
          sleep 2; \
          mvn -q -DskipTests -o -T 1C compile >/dev/null 2>&1; \
        done
      "
    networks:
      - clinique_net
    healthcheck:
      test: ["CMD-SHELL", "test -d /usr/src/app/target/classes/org/example/clinique/controller"]
      interval: 5s
      timeout: 3s
      start_period: 10s
      retries: 10

  

networks:
  clinique_net:

volumes:
  db_data:
  class_data: